package edge

// todo: 定义所有的IID

const (
	IID_ICoreWebView2FrameInfo2                              = "{56f85cfa-72c4-11ee-b962-0242ac120002}"
	IID_ICoreWebView2AcceleratorKeyPressedEventArgs2         = "{03b2c8c8-7799-4e34-bd66-ed26aa85f2bf}"
	IID_ICoreWebView2DevToolsProtocolEventReceivedEventArgs2 = "{2dc4959d-1494-4393-95ba-bea4cb9ebd1b}"
	IID_ICoreWebView2WebMessageReceivedEventArgs2            = "{06fc7ab7-c90c-4297-9389-33ca01cf6d5e}"
	IID_ICoreWebView2NavigationCompletedEventArgs2           = "{fdf8b738-ee1e-4db2-a329-8d7d7b74d792}"
	IID_ICoreWebView2PrintSettings2                          = "{CA7F0E1F-3484-41D1-8C1A-65CD44A63F8D}"
	IID_ICoreWebView2WebResourceRequestedEventArgs2          = "{9c562c24-b219-4d7f-92f6-b187fbbadd56}"

	IID_ICoreWebView2PermissionRequestedEventArgs2 = "{74d7127f-9de6-4200-8734-42d6fb4ff741}"
	IID_ICoreWebView2PermissionRequestedEventArgs3 = "{e61670bc-3dce-4177-86d2-c629ae3cb6ac}"

	IID_ICoreWebView2NavigationStartingEventArgs2 = "{9086be93-91aa-472d-a7e0-579f2ba006ad}"
	IID_ICoreWebView2NavigationStartingEventArgs3 = "{ddffe494-4942-4bd2-ab73-35b8ff40e19f}"

	IID_ICoreWebView2NewWindowRequestedEventArgs2 = "{bbc7baed-74c6-4c92-b63a-7f5aeae03de3}"
	IID_ICoreWebView2NewWindowRequestedEventArgs3 = "{842bed3c-6ad6-4dd9-b938-28c96667ad66}"

	IID_ICoreWebView2ProcessFailedEventArgs2 = "{4dab9422-46fa-4c3e-a5d2-41d2071d3680}"
	IID_ICoreWebView2ProcessFailedEventArgs3 = "{ab667428-094d-5fd1-b480-8b4c0fdbdf2f}"
)

const (
	IID_ICoreWebView2Profile2 = "{fa740d4b-5eae-4344-a8ad-74be31925397}"
	IID_ICoreWebView2Profile3 = "{b188e659-5685-4e05-bdba-fc640e0f1992}"
	IID_ICoreWebView2Profile4 = "{8f4ae680-192e-4ec8-833a-21cfadaef628}"
	IID_ICoreWebView2Profile5 = "{2ee5b76e-6e80-4df2-bcd3-d4ec3340a01b}"
	IID_ICoreWebView2Profile6 = "{BD82FA6A-1D65-4C33-B2B4-0393020CC61B}"
	IID_ICoreWebView2Profile7 = "{7b4c7906-a1aa-4cb4-b723-db09f813d541}"
	IID_ICoreWebView2Profile8 = "{fbf70c2f-eb1f-4383-85a0-163e92044011}"
)

const (
	IID_ICoreWebView2_2  = "{B4BC1926-7305-11EE-B962-0242AC120002}"
	IID_ICoreWebView2_3  = "{A0D6DF20-3B92-416D-AA0C-437A9C727857}"
	IID_ICoreWebView2_4  = "{20D02D59-6DF2-42DC-BD06-F98A694B1302}"
	IID_ICoreWebView2_5  = "{BEDB11B8-D63C-11EB-B8BC-0242AC130003}"
	IID_ICoreWebView2_6  = "{499AADAC-D92C-4589-8A75-111BFC167795}"
	IID_ICoreWebView2_7  = "{79C24D83-09A3-45AE-9418-487F32A58740}"
	IID_ICoreWebView2_8  = "{E9632730-6E1E-43AB-B7B8-7B2C9E62E094}"
	IID_ICoreWebView2_9  = "{4D7B2EAB-9FDC-468D-B998-A9260B5ED651}"
	IID_ICoreWebView2_10 = "{B1690564-6F5A-4983-8E48-31D1143FECDB}"
	IID_ICoreWebView2_11 = "{0BE78E56-C193-4051-B943-23B460C08BDB}"
	IID_ICoreWebView2_12 = "{35D69927-BCFA-4566-9349-6B3E0D154CAC}"
	IID_ICoreWebView2_13 = "{F75F09A8-667E-4983-88D6-C8773F315E84}"
	IID_ICoreWebView2_14 = "{6DAA4F10-4A90-4753-8898-77C5DF534165}"
	IID_ICoreWebView2_15 = "{517B2D1D-7DAE-4A66-A4F4-10352FFB9518}"
	IID_ICoreWebView2_16 = "{0EB34DC9-9F91-41E1-8639-95CD5943906B}"
	IID_ICoreWebView2_17 = "{702E75D4-FD44-434D-9D70-1A68A6B1192A}"
	IID_ICoreWebView2_18 = "{7A626017-28BE-49B2-B865-3BA2B3522D90}"
	IID_ICoreWebView2_19 = "{6921F954-79B0-437F-A997-C85811897C68}"
	IID_ICoreWebView2_20 = "{B4BC1926-7305-11EE-B962-0242AC120002}"
	IID_ICoreWebView2_21 = "{C4980DEA-587B-43B9-8143-3EF3BF552D95}"
	IID_ICoreWebView2_22 = "{DB75DFC7-A857-4632-A398-6969DDE26C0A}"
	IID_ICoreWebView2_23 = "{508F0DB5-90C4-5872-90A7-267A91377502}"
	IID_ICoreWebView2_24 = "{39A7AD55-4287-5CC1-88A1-C6F458593824}"
	IID_ICoreWebView2_25 = "{B5A86092-DF50-5B4F-A17B-6C8F8B40B771}"
	IID_ICoreWebView2_26 = "{806268B8-F897-5685-88E5-C45FCA0B1A48}"
	IID_ICoreWebView2_27 = "{00FBE33B-8C07-517C-AA23-0DDD4B5F6FA0}"
	IID_ICoreWebView2_28 = "{62e50381-5bf5-51a8-aae0-f20a3a9c8a90}"
)

const (
	IID_ICoreWebView2Controller2 = "{C979903E-D4CA-4228-92EB-47EE3FA96EAB}"
	IID_ICoreWebView2Controller3 = "{f9614724-5d2b-41dc-aef7-73d62b51543b}"
	IID_ICoreWebView2Controller4 = "{97d418d5-a426-4e49-a151-e1a10f327d9e}"
)

const (
	IID_ICoreWebView2ControllerOptions2 = "{06c991d8-9e7e-11ed-a8fc-0242ac120002}"
	IID_ICoreWebView2ControllerOptions3 = "{b32b191a-8998-57ca-b7cb-e04617e4ce4a}"
	IID_ICoreWebView2ControllerOptions4 = "{21eb052f-ad39-555e-824a-c87b091d4d36}"
)

const (
	IID_ICoreWebView2Settings2 = "{EE9A0F68-F46C-4E32-AC23-EF8CAC224D2A}"
	IID_ICoreWebView2Settings3 = "{FDB5AB74-AF33-4854-84F0-0A631DEB5EBA}"
	IID_ICoreWebView2Settings4 = "{CB56846C-4168-4D53-B04F-03B6D6796FF2}"
	IID_ICoreWebView2Settings5 = "{183E7052-1D03-43A0-AB99-98E043B66B39}"
	IID_ICoreWebView2Settings6 = "{11CB3ACD-9BC8-43B8-83BF-F40753714F87}"
	IID_ICoreWebView2Settings7 = "{488DC902-35EF-42D2-BC7D-94B65C4BC49C}"
	IID_ICoreWebView2Settings8 = "{9E6B0E8F-86AD-4E81-8147-A9B5EDB68650}"
	IID_ICoreWebView2Settings9 = "{0528A73B-E92D-49F4-927A-E547DDDAA37D}"
)

const (
	IID_ICoreWebView2Environment2  = "{41f3632b-5ef4-404f-ad82-2d606c5a9a21}"
	IID_ICoreWebView2Environment3  = "{80a22ae3-be7c-4ce2-afe1-5a50056cdeeb}"
	IID_ICoreWebView2Environment4  = "{20944379-6dcf-41d6-a0a0-abc0fc50de0d}"
	IID_ICoreWebView2Environment5  = "{319e423d-e0d7-4b8d-9254-ae9475de9b17}"
	IID_ICoreWebView2Environment6  = "{e59ee362-acbd-4857-9a8e-d3644d9459a9}"
	IID_ICoreWebView2Environment7  = "{43c22296-3bbd-43a4-9c00-5c0df6dd29a2}"
	IID_ICoreWebView2Environment8  = "{d6eb91dd-c3d2-45e5-bd29-6dc2bc4de9cf}"
	IID_ICoreWebView2Environment9  = "{f06f41bf-4b5a-49d8-b9f6-fa16cd29f274}"
	IID_ICoreWebView2Environment10 = "{ee0eb9df-6f12-46ce-b53f-3f47b9c928e0}"
	IID_ICoreWebView2Environment11 = "{f0913dc6-a0ec-42ef-9805-91dff3a2966a}"
	IID_ICoreWebView2Environment12 = "{f503db9b-739f-48dd-b151-fdfcf253f54e}"
	IID_ICoreWebView2Environment13 = "{af641f58-72b2-11ee-b962-0242ac120002}"
	IID_ICoreWebView2Environment14 = "{a5e9fad9-c875-59da-9bd7-473aa5ca1cef}"
	IID_ICoreWebView2Environment15 = "{2ac5ebfb-e654-5961-a667-7971885c7b27}"
)

const (
	IID_ICoreWebView2EnvironmentOptions2 = "{FF85C98A-1BA7-4A6B-90C8-2B752C89E9E2}"
	IID_ICoreWebView2EnvironmentOptions3 = "{4A5C436E-A9E3-4A2E-89C3-910D3513F5CC}"
	IID_ICoreWebView2EnvironmentOptions4 = "{AC52D13F-0D38-475A-9DCA-876580D6793E}"
	IID_ICoreWebView2EnvironmentOptions5 = "{0AE35D64-C47F-4464-814E-259C345D1501}"
	IID_ICoreWebView2EnvironmentOptions6 = "{57D29CC3-C84F-42A0-B0E2-EFFBD5E179DE}"
	IID_ICoreWebView2EnvironmentOptions7 = "{C48D539F-E39F-441C-AE68-1F66E570BDC5}"
	IID_ICoreWebView2EnvironmentOptions8 = "{7C7ECF51-E918-5CAF-853C-E9A2BCC27775}"
)

const (
	IID_ICoreWebView2Frame2 = "{7a6a5834-d185-4dbf-b63f-4a9bc43107d4}"
	IID_ICoreWebView2Frame3 = "{b50d82cc-cc28-481d-9614-cb048895e6a0}"
	IID_ICoreWebView2Frame4 = "{188782dc-92aa-4732-ab3c-fcc59f6f68b9}"
	IID_ICoreWebView2Frame5 = "{99d199c4-7305-11ee-b962-0242ac120002}"
	IID_ICoreWebView2Frame6 = "{0de611fd-31e9-5ddc-9d71-95eda26eff32}"
	IID_ICoreWebView2Frame7 = "{3598cfa2-d85d-5a9f-9228-4dde1f59ec64}"
)

// COREWEBVIEW2_BOUNDS_MODE 定义了边界模式类型
type COREWEBVIEW2_BOUNDS_MODE uint32

const (
	// COREWEBVIEW2_BOUNDS_MODE_USE_RAW_PIXELS 使用原始像素模式
	COREWEBVIEW2_BOUNDS_MODE_USE_RAW_PIXELS COREWEBVIEW2_BOUNDS_MODE = iota
	// COREWEBVIEW2_BOUNDS_MODE_USE_RASTERIZATION_SCALE 使用光栅化缩放模式
	COREWEBVIEW2_BOUNDS_MODE_USE_RASTERIZATION_SCALE
)

// COREWEBVIEW2_CHANNEL_SEARCH_KIND 定义了通道搜索的类型
type COREWEBVIEW2_CHANNEL_SEARCH_KIND uint32

const (
	// COREWEBVIEW2_CHANNEL_SEARCH_KIND_MOST_STABLE 表示搜索最稳定的通道
	COREWEBVIEW2_CHANNEL_SEARCH_KIND_MOST_STABLE COREWEBVIEW2_CHANNEL_SEARCH_KIND = iota
	// COREWEBVIEW2_CHANNEL_SEARCH_KIND_LEAST_STABLE 表示搜索最不稳定的通道
	COREWEBVIEW2_CHANNEL_SEARCH_KIND_LEAST_STABLE
)

// COREWEBVIEW2_RELEASE_CHANNELS 定义了 WebView2 的发布渠道类型
type COREWEBVIEW2_RELEASE_CHANNELS uint32

const (
	// COREWEBVIEW2_RELEASE_CHANNELS_NONE 无发布渠道
	COREWEBVIEW2_RELEASE_CHANNELS_NONE COREWEBVIEW2_RELEASE_CHANNELS = iota
	// COREWEBVIEW2_RELEASE_CHANNELS_STABLE 稳定版渠道
	COREWEBVIEW2_RELEASE_CHANNELS_STABLE
	// COREWEBVIEW2_RELEASE_CHANNELS_BETA 测试版渠道
	COREWEBVIEW2_RELEASE_CHANNELS_BETA
	// COREWEBVIEW2_RELEASE_CHANNELS_DEV 开发版渠道
	COREWEBVIEW2_RELEASE_CHANNELS_DEV
	// COREWEBVIEW2_RELEASE_CHANNELS_CANARY Canary 渠道
	COREWEBVIEW2_RELEASE_CHANNELS_CANARY
)

// COREWEBVIEW2_SCROLLBAR_STYLE 定义了滚动条的样式类型
type COREWEBVIEW2_SCROLLBAR_STYLE uint32

const (
	// COREWEBVIEW2_SCROLLBAR_STYLE_DEFAULT 默认滚动条样式
	COREWEBVIEW2_SCROLLBAR_STYLE_DEFAULT COREWEBVIEW2_SCROLLBAR_STYLE = iota
	// COREWEBVIEW2_SCROLLBAR_STYLE_FLUENT_OVERLAY Fluent 风格的覆盖式滚动条
	COREWEBVIEW2_SCROLLBAR_STYLE_FLUENT_OVERLAY
)

// COREWEBVIEW2_KEY_EVENT_KIND 定义了键盘事件的类型, 用于标识不同种类的键盘输入事件.
type COREWEBVIEW2_KEY_EVENT_KIND uint32

const (
	// COREWEBVIEW2_KEY_EVENT_KIND_KEY_DOWN 表示按键按下事件
	COREWEBVIEW2_KEY_EVENT_KIND_KEY_DOWN COREWEBVIEW2_KEY_EVENT_KIND = iota
	// COREWEBVIEW2_KEY_EVENT_KIND_KEY_UP 表示按键释放事件
	COREWEBVIEW2_KEY_EVENT_KIND_KEY_UP
	// COREWEBVIEW2_KEY_EVENT_KIND_SYSTEM_KEY_DOWN 表示系统按键按下事件
	COREWEBVIEW2_KEY_EVENT_KIND_SYSTEM_KEY_DOWN
	// COREWEBVIEW2_KEY_EVENT_KIND_SYSTEM_KEY_UP 表示系统按键释放事件
	COREWEBVIEW2_KEY_EVENT_KIND_SYSTEM_KEY_UP
)

// COREWEBVIEW2_PERMISSION_STATE 表示 WebView2 权限的状态
type COREWEBVIEW2_PERMISSION_STATE uint32

const (
	// COREWEBVIEW2_PERMISSION_STATE_DEFAULT 使用默认的权限设置
	COREWEBVIEW2_PERMISSION_STATE_DEFAULT COREWEBVIEW2_PERMISSION_STATE = iota
	// COREWEBVIEW2_PERMISSION_STATE_ALLOW 允许权限
	COREWEBVIEW2_PERMISSION_STATE_ALLOW
	// COREWEBVIEW2_PERMISSION_STATE_DENY 拒绝权限
	COREWEBVIEW2_PERMISSION_STATE_DENY
)

// COREWEBVIEW2_MOVE_FOCUS_REASON 定义了焦点移动的原因类型
type COREWEBVIEW2_MOVE_FOCUS_REASON uint32

const (
	// COREWEBVIEW2_MOVE_FOCUS_REASON_PROGRAMMATIC 表示通过程序代码移动焦点
	COREWEBVIEW2_MOVE_FOCUS_REASON_PROGRAMMATIC COREWEBVIEW2_MOVE_FOCUS_REASON = iota
	// COREWEBVIEW2_MOVE_FOCUS_REASON_NEXT 表示移动到下一个焦点元素
	COREWEBVIEW2_MOVE_FOCUS_REASON_NEXT
	// COREWEBVIEW2_MOVE_FOCUS_REASON_PREVIOUS 表示移动到上一个焦点元素
	COREWEBVIEW2_MOVE_FOCUS_REASON_PREVIOUS
)

// COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND 定义了资源访问的类型
type COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND uint32

const (
	// COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_DENY 拒绝访问。
	COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_DENY COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND = iota
	// COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_ALLOW 允许访问。
	COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_ALLOW
	// COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_DENY_CORS 拒绝跨域访问。
	COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_DENY_CORS
)

// COREWEBVIEW2_WEB_RESOURCE_CONTEXT 定义了 WebView2 中 Web 资源的上下文类型.
//
// 这些常量用于标识不同类型的 Web 资源请求.
type COREWEBVIEW2_WEB_RESOURCE_CONTEXT uint32

const (
	// 所有类型的资源
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_ALL COREWEBVIEW2_WEB_RESOURCE_CONTEXT = iota
	// HTML 文档
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_DOCUMENT
	// CSS 样式表
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_STYLESHEET
	// 图片资源
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_IMAGE
	// 媒体资源(音频/视频)
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_MEDIA
	// 字体资源
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_FONT
	// JavaScript 脚本
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_SCRIPT
	// XMLHttpRequest 请求
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_XML_HTTP_REQUEST
	// Fetch API 请求
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_FETCH
	// 文本轨道(字幕等)
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_TEXT_TRACK
	// EventSource API 请求
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_EVENT_SOURCE
	// WebSocket 连接
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_WEBSOCKET
	// Web 应用清单文件
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_MANIFEST
	// 签名交换
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_SIGNED_EXCHANGE
	// Ping 请求
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_PING
	// CSP 违规报告
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_CSP_VIOLATION_REPORT
	// 其他类型的资源
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_OTHER
)

// COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS 定义了 Web 资源请求的来源类型
type COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS uint32

const (
	// COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_NONE 无来源类型
	COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_NONE COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS = 0
	// COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_DOCUMENT 文档来源
	COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_DOCUMENT COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS = 0x1
	// COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_SHARED_WORKER 共享 Worker 来源
	COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_SHARED_WORKER COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS = 0x2
	// COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_SERVICE_WORKER 服务 Worker 来源
	COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_SERVICE_WORKER COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS = 0x4
	// COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_ALL 所有来源类型
	COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_ALL COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS = 0xffffffff
)

// COREWEBVIEW2_COOKIE_SAME_SITE_KIND 表示 Cookie 的 SameSite 状态。
type COREWEBVIEW2_COOKIE_SAME_SITE_KIND uint32

const (
	// COREWEBVIEW2_COOKIE_SAME_SITE_KIND_NONE: Cookie 将在所有上下文中发送，即允许跨站点发送。
	COREWEBVIEW2_COOKIE_SAME_SITE_KIND_NONE COREWEBVIEW2_COOKIE_SAME_SITE_KIND = iota
	// COREWEBVIEW2_COOKIE_SAME_SITE_KIND_LAX: Cookie 不会在跨站点请求中发送，除非是导航到目标网站的顶级导航。
	COREWEBVIEW2_COOKIE_SAME_SITE_KIND_LAX
	// COREWEBVIEW2_COOKIE_SAME_SITE_KIND_STRICT: Cookie 仅在同一站点上下文中发送。
	COREWEBVIEW2_COOKIE_SAME_SITE_KIND_STRICT
)

// COREWEBVIEW2_WEB_ERROR_STATUS 表示导航错误的状态码
type COREWEBVIEW2_WEB_ERROR_STATUS uint32

const (
	// COREWEBVIEW2_WEB_ERROR_STATUS_UNKNOWN 未知错误
	COREWEBVIEW2_WEB_ERROR_STATUS_UNKNOWN COREWEBVIEW2_WEB_ERROR_STATUS = iota
	// COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_COMMON_NAME_IS_INCORRECT 证书通用名称不正确
	COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_COMMON_NAME_IS_INCORRECT
	// COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_EXPIRED 证书已过期
	COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_EXPIRED
	// COREWEBVIEW2_WEB_ERROR_STATUS_CLIENT_CERTIFICATE_CONTAINS_ERRORS 客户端证书包含错误
	COREWEBVIEW2_WEB_ERROR_STATUS_CLIENT_CERTIFICATE_CONTAINS_ERRORS
	// COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_REVOKED 证书已被吊销
	COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_REVOKED
	// COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_IS_INVALID 证书无效
	COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_IS_INVALID
	// COREWEBVIEW2_WEB_ERROR_STATUS_SERVER_UNREACHABLE 服务器不可达
	COREWEBVIEW2_WEB_ERROR_STATUS_SERVER_UNREACHABLE
	// COREWEBVIEW2_WEB_ERROR_STATUS_TIMEOUT 连接超时
	COREWEBVIEW2_WEB_ERROR_STATUS_TIMEOUT
	// COREWEBVIEW2_WEB_ERROR_STATUS_ERROR_HTTP_INVALID_SERVER_RESPONSE 无效的服务器响应
	COREWEBVIEW2_WEB_ERROR_STATUS_ERROR_HTTP_INVALID_SERVER_RESPONSE
	// COREWEBVIEW2_WEB_ERROR_STATUS_CONNECTION_ABORTED 连接中止
	COREWEBVIEW2_WEB_ERROR_STATUS_CONNECTION_ABORTED
	// COREWEBVIEW2_WEB_ERROR_STATUS_CONNECTION_RESET 连接重置
	COREWEBVIEW2_WEB_ERROR_STATUS_CONNECTION_RESET
	// COREWEBVIEW2_WEB_ERROR_STATUS_DISCONNECTED 已断开连接
	COREWEBVIEW2_WEB_ERROR_STATUS_DISCONNECTED
	// COREWEBVIEW2_WEB_ERROR_STATUS_CANNOT_CONNECT 无法连接
	COREWEBVIEW2_WEB_ERROR_STATUS_CANNOT_CONNECT
	// COREWEBVIEW2_WEB_ERROR_STATUS_HOST_NAME_NOT_RESOLVED 主机名无法解析
	COREWEBVIEW2_WEB_ERROR_STATUS_HOST_NAME_NOT_RESOLVED
	// COREWEBVIEW2_WEB_ERROR_STATUS_OPERATION_CANCELED 操作已取消
	COREWEBVIEW2_WEB_ERROR_STATUS_OPERATION_CANCELED
	// COREWEBVIEW2_WEB_ERROR_STATUS_REDIRECT_FAILED 重定向失败
	COREWEBVIEW2_WEB_ERROR_STATUS_REDIRECT_FAILED
	// COREWEBVIEW2_WEB_ERROR_STATUS_UNEXPECTED_ERROR 意外错误
	COREWEBVIEW2_WEB_ERROR_STATUS_UNEXPECTED_ERROR
	// COREWEBVIEW2_WEB_ERROR_STATUS_VALID_AUTHENTICATION_CREDENTIALS_REQUIRED 指示提示用户登录，等待用户操作
	COREWEBVIEW2_WEB_ERROR_STATUS_VALID_AUTHENTICATION_CREDENTIALS_REQUIRED
	// COREWEBVIEW2_WEB_ERROR_STATUS_VALID_PROXY_AUTHENTICATION_REQUIRED 指示用户缺少代理服务器的正确身份验证凭据
	COREWEBVIEW2_WEB_ERROR_STATUS_VALID_PROXY_AUTHENTICATION_REQUIRED
)

// COREWEBVIEW2_PERMISSION_KIND 定义了 WebView2 中的权限类型
type COREWEBVIEW2_PERMISSION_KIND uint32

const (
	// COREWEBVIEW2_PERMISSION_KIND_UNKNOWN_PERMISSION 未知权限
	COREWEBVIEW2_PERMISSION_KIND_UNKNOWN_PERMISSION COREWEBVIEW2_PERMISSION_KIND = iota
	// COREWEBVIEW2_PERMISSION_KIND_MICROPHONE 麦克风权限
	COREWEBVIEW2_PERMISSION_KIND_MICROPHONE
	// COREWEBVIEW2_PERMISSION_KIND_CAMERA 摄像头权限
	COREWEBVIEW2_PERMISSION_KIND_CAMERA
	// COREWEBVIEW2_PERMISSION_KIND_GEOLOCATION 地理位置权限
	COREWEBVIEW2_PERMISSION_KIND_GEOLOCATION
	// COREWEBVIEW2_PERMISSION_KIND_NOTIFICATIONS 通知权限
	COREWEBVIEW2_PERMISSION_KIND_NOTIFICATIONS
	// COREWEBVIEW2_PERMISSION_KIND_OTHER_SENSORS 其他传感器权限
	COREWEBVIEW2_PERMISSION_KIND_OTHER_SENSORS
	// COREWEBVIEW2_PERMISSION_KIND_CLIPBOARD_READ 剪贴板读取权限
	COREWEBVIEW2_PERMISSION_KIND_CLIPBOARD_READ
	// COREWEBVIEW2_PERMISSION_KIND_MULTIPLE_AUTOMATIC_DOWNLOADS 表示自动下载多个文件的权限
	COREWEBVIEW2_PERMISSION_KIND_MULTIPLE_AUTOMATIC_DOWNLOADS
	// COREWEBVIEW2_PERMISSION_KIND_FILE_READ_WRITE 表示读写设备上的文件或文件夹的权限
	COREWEBVIEW2_PERMISSION_KIND_FILE_READ_WRITE
	// COREWEBVIEW2_PERMISSION_KIND_AUTOPLAY 表示在网站上自动播放音频和视频的权限
	COREWEBVIEW2_PERMISSION_KIND_AUTOPLAY
	// COREWEBVIEW2_PERMISSION_KIND_LOCAL_FONTS 表示使用设备上字体的权限
	COREWEBVIEW2_PERMISSION_KIND_LOCAL_FONTS
	// COREWEBVIEW2_PERMISSION_KIND_MIDI_SYSTEM_EXCLUSIVE_MESSAGES 表示向/从MIDI设备发送和接收系统专有消息的权限
	COREWEBVIEW2_PERMISSION_KIND_MIDI_SYSTEM_EXCLUSIVE_MESSAGES
	// COREWEBVIEW2_PERMISSION_KIND_WINDOW_MANAGEMENT 表示在屏幕上打开和放置窗口的权限
	COREWEBVIEW2_PERMISSION_KIND_WINDOW_MANAGEMENT
)

// COREWEBVIEW2_PDF_TOOLBAR_ITEMS 定义了 PDF 工具栏中可用的项目
type COREWEBVIEW2_PDF_TOOLBAR_ITEMS uint32

const (
	// COREWEBVIEW2_PDF_TOOLBAR_ITEMS_NONE 不显示任何工具栏项目
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_NONE COREWEBVIEW2_PDF_TOOLBAR_ITEMS = iota
	// COREWEBVIEW2_PDF_TOOLBAR_ITEMS_SAVE 保存按钮
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_SAVE
	// COREWEBVIEW2_PDF_TOOLBAR_ITEMS_PRINT 打印按钮
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_PRINT
	// COREWEBVIEW2_PDF_TOOLBAR_ITEMS_SAVE_AS 另存为按钮
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_SAVE_AS
	// COREWEBVIEW2_PDF_TOOLBAR_ITEMS_ZOOM_IN 放大按钮
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_ZOOM_IN
	// COREWEBVIEW2_PDF_TOOLBAR_ITEMS_ZOOM_OUT 缩小按钮
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_ZOOM_OUT
	// COREWEBVIEW2_PDF_TOOLBAR_ITEMS_ROTATE 旋转按钮
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_ROTATE
	// COREWEBVIEW2_PDF_TOOLBAR_ITEMS_FIT_PAGE 适应页面按钮
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_FIT_PAGE
	// COREWEBVIEW2_PDF_TOOLBAR_ITEMS_PAGE_LAYOUT 页面布局按钮
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_PAGE_LAYOUT
	// COREWEBVIEW2_PDF_TOOLBAR_ITEMS_BOOKMARKS 书签按钮
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_BOOKMARKS
	// COREWEBVIEW2_PDF_TOOLBAR_ITEMS_PAGE_SELECTOR 页面选择按钮
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_PAGE_SELECTOR
	// COREWEBVIEW2_PDF_TOOLBAR_ITEMS_SEARCH 搜索按钮
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_SEARCH
	// COREWEBVIEW2_PDF_TOOLBAR_ITEMS_FULL_SCREEN 全屏按钮
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_FULL_SCREEN
	// COREWEBVIEW2_PDF_TOOLBAR_ITEMS_MORE_SETTINGS 更多设置按钮
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_MORE_SETTINGS
)

// COREWEBVIEW2_TRACKING_PREVENTION_LEVEL 定义了跟踪防护的级别
type COREWEBVIEW2_TRACKING_PREVENTION_LEVEL uint32

const (
	// COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_NONE 关闭跟踪防护
	COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_NONE COREWEBVIEW2_TRACKING_PREVENTION_LEVEL = iota
	// COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_BASIC 最低限制级别的跟踪防护
	COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_BASIC
	// COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_BALANCED 默认级别的跟踪防护
	COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_BALANCED
	// COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_STRICT 最严格级别的跟踪防护
	COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_STRICT
)

// COREWEBVIEW2_BROWSING_DATA_KINDS 定义了浏览数据的类型
type COREWEBVIEW2_BROWSING_DATA_KINDS uint32

const (
	// COREWEBVIEW2_BROWSING_DATA_KINDS_FILE_SYSTEMS 文件系统数据
	COREWEBVIEW2_BROWSING_DATA_KINDS_FILE_SYSTEMS COREWEBVIEW2_BROWSING_DATA_KINDS = 0x1
	// COREWEBVIEW2_BROWSING_DATA_KINDS_INDEXED_DB IndexedDB 数据
	COREWEBVIEW2_BROWSING_DATA_KINDS_INDEXED_DB COREWEBVIEW2_BROWSING_DATA_KINDS = 0x2
	// COREWEBVIEW2_BROWSING_DATA_KINDS_LOCAL_STORAGE 本地存储数据
	COREWEBVIEW2_BROWSING_DATA_KINDS_LOCAL_STORAGE COREWEBVIEW2_BROWSING_DATA_KINDS = 0x4
	// COREWEBVIEW2_BROWSING_DATA_KINDS_WEB_SQL WebSQL 数据
	COREWEBVIEW2_BROWSING_DATA_KINDS_WEB_SQL COREWEBVIEW2_BROWSING_DATA_KINDS = 0x8
	// COREWEBVIEW2_BROWSING_DATA_KINDS_CACHE_STORAGE 缓存存储数据
	COREWEBVIEW2_BROWSING_DATA_KINDS_CACHE_STORAGE COREWEBVIEW2_BROWSING_DATA_KINDS = 0x10
	// COREWEBVIEW2_BROWSING_DATA_KINDS_ALL_DOM_STORAGE 所有 DOM 存储数据
	COREWEBVIEW2_BROWSING_DATA_KINDS_ALL_DOM_STORAGE COREWEBVIEW2_BROWSING_DATA_KINDS = 0x20
	// COREWEBVIEW2_BROWSING_DATA_KINDS_COOKIES Cookie 数据
	COREWEBVIEW2_BROWSING_DATA_KINDS_COOKIES COREWEBVIEW2_BROWSING_DATA_KINDS = 0x40
	// COREWEBVIEW2_BROWSING_DATA_KINDS_ALL_SITE 所有站点数据
	COREWEBVIEW2_BROWSING_DATA_KINDS_ALL_SITE COREWEBVIEW2_BROWSING_DATA_KINDS = 0x80
	// COREWEBVIEW2_BROWSING_DATA_KINDS_DISK_CACHE 磁盘缓存数据
	COREWEBVIEW2_BROWSING_DATA_KINDS_DISK_CACHE COREWEBVIEW2_BROWSING_DATA_KINDS = 0x100
	// COREWEBVIEW2_BROWSING_DATA_KINDS_DOWNLOAD_HISTORY 下载历史数据
	COREWEBVIEW2_BROWSING_DATA_KINDS_DOWNLOAD_HISTORY COREWEBVIEW2_BROWSING_DATA_KINDS = 0x200
	// COREWEBVIEW2_BROWSING_DATA_KINDS_GENERAL_AUTOFILL 通用自动填充数据
	COREWEBVIEW2_BROWSING_DATA_KINDS_GENERAL_AUTOFILL COREWEBVIEW2_BROWSING_DATA_KINDS = 0x400
	// COREWEBVIEW2_BROWSING_DATA_KINDS_PASSWORD_AUTOSAVE 密码自动保存数据
	COREWEBVIEW2_BROWSING_DATA_KINDS_PASSWORD_AUTOSAVE COREWEBVIEW2_BROWSING_DATA_KINDS = 0x800
	// COREWEBVIEW2_BROWSING_DATA_KINDS_BROWSING_HISTORY 浏览历史数据
	COREWEBVIEW2_BROWSING_DATA_KINDS_BROWSING_HISTORY COREWEBVIEW2_BROWSING_DATA_KINDS = 0x1000
	// COREWEBVIEW2_BROWSING_DATA_KINDS_SETTINGS 设置数据
	COREWEBVIEW2_BROWSING_DATA_KINDS_SETTINGS COREWEBVIEW2_BROWSING_DATA_KINDS = 0x2000
	// COREWEBVIEW2_BROWSING_DATA_KINDS_ALL_PROFILE 所有配置文件数据
	COREWEBVIEW2_BROWSING_DATA_KINDS_ALL_PROFILE COREWEBVIEW2_BROWSING_DATA_KINDS = 0x4000
	// COREWEBVIEW2_BROWSING_DATA_KINDS_SERVICE_WORKERS Service Worker 数据
	COREWEBVIEW2_BROWSING_DATA_KINDS_SERVICE_WORKERS COREWEBVIEW2_BROWSING_DATA_KINDS = 0x8000
)

// COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT 定义了捕获预览图像的格式类型
type COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT uint32

const (
	// COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT_PNG PNG 图像格式
	COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT_PNG COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT = iota
	// COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT_JPEG JPEG 图像格式
	COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT_JPEG
)

// COREWEBVIEW2_PROCESS_FAILED_KIND 定义了进程失败的类型
type COREWEBVIEW2_PROCESS_FAILED_KIND uint32

const (
	// COREWEBVIEW2_PROCESS_FAILED_KIND_BROWSER_PROCESS_EXITED 浏览器进程退出
	COREWEBVIEW2_PROCESS_FAILED_KIND_BROWSER_PROCESS_EXITED COREWEBVIEW2_PROCESS_FAILED_KIND = iota
	// COREWEBVIEW2_PROCESS_FAILED_KIND_RENDER_PROCESS_EXITED 渲染进程退出
	COREWEBVIEW2_PROCESS_FAILED_KIND_RENDER_PROCESS_EXITED
	// COREWEBVIEW2_PROCESS_FAILED_KIND_RENDER_PROCESS_UNRESPONSIVE 渲染进程无响应
	COREWEBVIEW2_PROCESS_FAILED_KIND_RENDER_PROCESS_UNRESPONSIVE
	// COREWEBVIEW2_PROCESS_FAILED_KIND_FRAME_RENDER_PROCESS_EXITED 帧渲染进程退出
	COREWEBVIEW2_PROCESS_FAILED_KIND_FRAME_RENDER_PROCESS_EXITED
	// COREWEBVIEW2_PROCESS_FAILED_KIND_UTILITY_PROCESS_EXITED 工具进程退出
	COREWEBVIEW2_PROCESS_FAILED_KIND_UTILITY_PROCESS_EXITED
	// COREWEBVIEW2_PROCESS_FAILED_KIND_SANDBOX_HELPER_PROCESS_EXITED 沙箱辅助进程退出
	COREWEBVIEW2_PROCESS_FAILED_KIND_SANDBOX_HELPER_PROCESS_EXITED
	// COREWEBVIEW2_PROCESS_FAILED_KIND_GPU_PROCESS_EXITED GPU进程退出
	COREWEBVIEW2_PROCESS_FAILED_KIND_GPU_PROCESS_EXITED
	// COREWEBVIEW2_PROCESS_FAILED_KIND_PPAPI_PLUGIN_PROCESS_EXITED PPAPI插件进程退出
	COREWEBVIEW2_PROCESS_FAILED_KIND_PPAPI_PLUGIN_PROCESS_EXITED
	// COREWEBVIEW2_PROCESS_FAILED_KIND_PPAPI_BROKER_PROCESS_EXITED PPAPI代理进程退出
	COREWEBVIEW2_PROCESS_FAILED_KIND_PPAPI_BROKER_PROCESS_EXITED
	// COREWEBVIEW2_PROCESS_FAILED_KIND_UNKNOWN_PROCESS_EXITED 未知进程退出
	COREWEBVIEW2_PROCESS_FAILED_KIND_UNKNOWN_PROCESS_EXITED
)

// COREWEBVIEW2_SCRIPT_DIALOG_KIND 定义了脚本对话框的类型
type COREWEBVIEW2_SCRIPT_DIALOG_KIND uint32

const (
	// COREWEBVIEW2_SCRIPT_DIALOG_KIND_ALERT 表示警告对话框
	COREWEBVIEW2_SCRIPT_DIALOG_KIND_ALERT COREWEBVIEW2_SCRIPT_DIALOG_KIND = iota
	// COREWEBVIEW2_SCRIPT_DIALOG_KIND_CONFIRM 表示确认对话框
	COREWEBVIEW2_SCRIPT_DIALOG_KIND_CONFIRM
	// COREWEBVIEW2_SCRIPT_DIALOG_KIND_PROMPT 表示提示输入对话框
	COREWEBVIEW2_SCRIPT_DIALOG_KIND_PROMPT
	// COREWEBVIEW2_SCRIPT_DIALOG_KIND_BEFOREUNLOAD 表示页面关闭前的确认对话框
	COREWEBVIEW2_SCRIPT_DIALOG_KIND_BEFOREUNLOAD
)

// COREWEBVIEW2_SHARED_BUFFER_ACCESS 定义了共享缓冲区的访问权限类型
type COREWEBVIEW2_SHARED_BUFFER_ACCESS uint32

const (
	// COREWEBVIEW2_SHARED_BUFFER_ACCESS_READ_ONLY 表示只读访问权限
	COREWEBVIEW2_SHARED_BUFFER_ACCESS_READ_ONLY COREWEBVIEW2_SHARED_BUFFER_ACCESS = iota
	// COREWEBVIEW2_SHARED_BUFFER_ACCESS_READ_WRITE 表示读写访问权限
	COREWEBVIEW2_SHARED_BUFFER_ACCESS_READ_WRITE
)

// COREWEBVIEW2_DEFAULT_DOWNLOAD_DIALOG_CORNER_ALIGNMENT 定义了默认下载对话框的角落对齐方式
type COREWEBVIEW2_DEFAULT_DOWNLOAD_DIALOG_CORNER_ALIGNMENT uint32

const (
	// COREWEBVIEW2_DEFAULT_DOWNLOAD_DIALOG_CORNER_ALIGNMENT_TOP_LEFT 左上角对齐
	COREWEBVIEW2_DEFAULT_DOWNLOAD_DIALOG_CORNER_ALIGNMENT_TOP_LEFT COREWEBVIEW2_DEFAULT_DOWNLOAD_DIALOG_CORNER_ALIGNMENT = iota
	// COREWEBVIEW2_DEFAULT_DOWNLOAD_DIALOG_CORNER_ALIGNMENT_TOP_RIGHT 右上角对齐
	COREWEBVIEW2_DEFAULT_DOWNLOAD_DIALOG_CORNER_ALIGNMENT_TOP_RIGHT
	// COREWEBVIEW2_DEFAULT_DOWNLOAD_DIALOG_CORNER_ALIGNMENT_BOTTOM_LEFT 左下角对齐
	COREWEBVIEW2_DEFAULT_DOWNLOAD_DIALOG_CORNER_ALIGNMENT_BOTTOM_LEFT
	// COREWEBVIEW2_DEFAULT_DOWNLOAD_DIALOG_CORNER_ALIGNMENT_BOTTOM_RIGHT 右下角对齐
	COREWEBVIEW2_DEFAULT_DOWNLOAD_DIALOG_CORNER_ALIGNMENT_BOTTOM_RIGHT
)

// COREWEBVIEW2_DOWNLOAD_STATE 定义了下载状态类型
type COREWEBVIEW2_DOWNLOAD_STATE uint32

const (
	// COREWEBVIEW2_DOWNLOAD_STATE_IN_PROGRESS 表示下载正在进行中
	COREWEBVIEW2_DOWNLOAD_STATE_IN_PROGRESS COREWEBVIEW2_DOWNLOAD_STATE = iota
	// COREWEBVIEW2_DOWNLOAD_STATE_INTERRUPTED 表示下载被中断
	COREWEBVIEW2_DOWNLOAD_STATE_INTERRUPTED
	// COREWEBVIEW2_DOWNLOAD_STATE_COMPLETED 表示下载已完成
	COREWEBVIEW2_DOWNLOAD_STATE_COMPLETED
)

// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON 定义了下载中断的原因类型
type COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON uint32

const (
	// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NONE 无中断原因
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NONE COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = iota
	// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_FAILED 文件操作失败
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_FAILED
	// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_ACCESS_DENIED 文件访问被拒绝
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_ACCESS_DENIED
	// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_NO_SPACE 磁盘空间不足
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_NO_SPACE
	// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_NAME_TOO_LONG 文件名过长
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_NAME_TOO_LONG
	// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_TOO_LARGE 文件过大
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_TOO_LARGE
	// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_MALICIOUS 检测到恶意文件
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_MALICIOUS
	// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_TRANSIENT_ERROR 临时文件错误
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_TRANSIENT_ERROR
	// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_BLOCKED_BY_POLICY 文件被策略阻止
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_BLOCKED_BY_POLICY
	// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_SECURITY_CHECK_FAILED 文件安全检查失败
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_SECURITY_CHECK_FAILED
	// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_TOO_SHORT 文件过短
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_TOO_SHORT
	// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_HASH_MISMATCH 文件哈希不匹配
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_HASH_MISMATCH
	// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NETWORK_FAILED 网络连接失败
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NETWORK_FAILED
	// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NETWORK_TIMEOUT 网络超时
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NETWORK_TIMEOUT
	// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NETWORK_DISCONNECTED 网络断开
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NETWORK_DISCONNECTED
	// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NETWORK_SERVER_DOWN 服务器宕机
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NETWORK_SERVER_DOWN
	// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NETWORK_INVALID_REQUEST 无效的网络请求
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NETWORK_INVALID_REQUEST
	// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_FAILED 服务器错误
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_FAILED
	// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_NO_RANGE 服务器不支持范围请求
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_NO_RANGE
	// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_BAD_CONTENT 服务器返回错误内容
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_BAD_CONTENT
	// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_UNAUTHORIZED 未授权访问服务器
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_UNAUTHORIZED
	// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_CERTIFICATE_PROBLEM 服务器证书问题
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_CERTIFICATE_PROBLEM
	// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_FORBIDDEN 服务器禁止访问
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_FORBIDDEN
	// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_UNEXPECTED_RESPONSE 服务器返回意外响应
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_UNEXPECTED_RESPONSE
	// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_CONTENT_LENGTH_MISMATCH 服务器内容长度不匹配
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_CONTENT_LENGTH_MISMATCH
	// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_CROSS_ORIGIN_REDIRECT 跨域重定向
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_CROSS_ORIGIN_REDIRECT
	// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_USER_CANCELED 用户取消下载
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_USER_CANCELED
	// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_USER_SHUTDOWN 用户关闭程序
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_USER_SHUTDOWN
	// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_USER_PAUSED 用户暂停下载
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_USER_PAUSED
	// COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_DOWNLOAD_PROCESS_CRASHED 下载进程崩溃
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_DOWNLOAD_PROCESS_CRASHED
)

// COREWEBVIEW2_CLIENT_CERTIFICATE_KIND 定义了客户端证书的类型
type COREWEBVIEW2_CLIENT_CERTIFICATE_KIND uint32

const (
	// COREWEBVIEW2_CLIENT_CERTIFICATE_KIND_SMART_CARD 智能卡证书
	COREWEBVIEW2_CLIENT_CERTIFICATE_KIND_SMART_CARD COREWEBVIEW2_CLIENT_CERTIFICATE_KIND = iota
	// COREWEBVIEW2_CLIENT_CERTIFICATE_KIND_PIN PIN码证书
	COREWEBVIEW2_CLIENT_CERTIFICATE_KIND_PIN
	// COREWEBVIEW2_CLIENT_CERTIFICATE_KIND_OTHER 其他类型证书
	COREWEBVIEW2_CLIENT_CERTIFICATE_KIND_OTHER
)

// COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND 定义了上下文菜单目标的类型
type COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND uint32

const (
	// COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_PAGE 页面目标
	COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_PAGE COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND = iota
	// COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_IMAGE 图片目标
	COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_IMAGE
	// COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_SELECTED_TEXT 选中的文本目标
	COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_SELECTED_TEXT
	// COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_AUDIO 音频目标
	COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_AUDIO
	// COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_VIDEO 视频目标
	COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_VIDEO
)

// COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND 定义了上下文菜单项的类型
type COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND uint32

const (
	// COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_COMMAND 普通命令菜单项
	COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_COMMAND COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND = iota
	// COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_CHECK_BOX 复选框菜单项
	COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_CHECK_BOX
	// COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_RADIO 单选按钮菜单项
	COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_RADIO
	// COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_SEPARATOR 分隔线菜单项
	COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_SEPARATOR
	// COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_SUBMENU 子菜单项
	COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_SUBMENU
)

// COREWEBVIEW2_MOUSE_EVENT_KIND 定义了鼠标事件的类型
type COREWEBVIEW2_MOUSE_EVENT_KIND uint32

const (
	// 水平滚轮事件
	COREWEBVIEW2_MOUSE_EVENT_KIND_HORIZONTAL_WHEEL COREWEBVIEW2_MOUSE_EVENT_KIND = 526
	// 左键双击事件
	COREWEBVIEW2_MOUSE_EVENT_KIND_LEFT_BUTTON_DOUBLE_CLICK COREWEBVIEW2_MOUSE_EVENT_KIND = 515
	// 左键按下事件
	COREWEBVIEW2_MOUSE_EVENT_KIND_LEFT_BUTTON_DOWN COREWEBVIEW2_MOUSE_EVENT_KIND = 513
	// 左键释放事件
	COREWEBVIEW2_MOUSE_EVENT_KIND_LEFT_BUTTON_UP COREWEBVIEW2_MOUSE_EVENT_KIND = 514
	// 鼠标离开事件
	COREWEBVIEW2_MOUSE_EVENT_KIND_LEAVE COREWEBVIEW2_MOUSE_EVENT_KIND = 675
	// 中键双击事件
	COREWEBVIEW2_MOUSE_EVENT_KIND_MIDDLE_BUTTON_DOUBLE_CLICK COREWEBVIEW2_MOUSE_EVENT_KIND = 521
	// 中键按下事件
	COREWEBVIEW2_MOUSE_EVENT_KIND_MIDDLE_BUTTON_DOWN COREWEBVIEW2_MOUSE_EVENT_KIND = 519
	// 中键释放事件
	COREWEBVIEW2_MOUSE_EVENT_KIND_MIDDLE_BUTTON_UP COREWEBVIEW2_MOUSE_EVENT_KIND = 520
	// 鼠标移动事件
	COREWEBVIEW2_MOUSE_EVENT_KIND_MOVE COREWEBVIEW2_MOUSE_EVENT_KIND = 512
	// 右键双击事件
	COREWEBVIEW2_MOUSE_EVENT_KIND_RIGHT_BUTTON_DOUBLE_CLICK COREWEBVIEW2_MOUSE_EVENT_KIND = 518
	// 右键按下事件
	COREWEBVIEW2_MOUSE_EVENT_KIND_RIGHT_BUTTON_DOWN COREWEBVIEW2_MOUSE_EVENT_KIND = 516
	// 右键释放事件
	COREWEBVIEW2_MOUSE_EVENT_KIND_RIGHT_BUTTON_UP COREWEBVIEW2_MOUSE_EVENT_KIND = 517
	// 滚轮事件
	COREWEBVIEW2_MOUSE_EVENT_KIND_WHEEL COREWEBVIEW2_MOUSE_EVENT_KIND = 522
	// X键双击事件
	COREWEBVIEW2_MOUSE_EVENT_KIND_X_BUTTON_DOUBLE_CLICK COREWEBVIEW2_MOUSE_EVENT_KIND = 525
	// X键按下事件
	COREWEBVIEW2_MOUSE_EVENT_KIND_X_BUTTON_DOWN COREWEBVIEW2_MOUSE_EVENT_KIND = 523
	// X键释放事件
	COREWEBVIEW2_MOUSE_EVENT_KIND_X_BUTTON_UP COREWEBVIEW2_MOUSE_EVENT_KIND = 524
	// 非客户区右键按下事件
	COREWEBVIEW2_MOUSE_EVENT_KIND_NON_CLIENT_RIGHT_BUTTON_DOWN COREWEBVIEW2_MOUSE_EVENT_KIND = 164
	// 非客户区右键释放事件
	COREWEBVIEW2_MOUSE_EVENT_KIND_NON_CLIENT_RIGHT_BUTTON_UP COREWEBVIEW2_MOUSE_EVENT_KIND = 165
)

// COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS 定义了鼠标事件的虚拟按键状态
type COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS uint32

const (
	// COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_NONE 无按键按下
	COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_NONE COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS = 0
	// COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_LEFT_BUTTON 左键按下
	COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_LEFT_BUTTON COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS = 0x1
	// COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_RIGHT_BUTTON 右键按下
	COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_RIGHT_BUTTON COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS = 0x2
	// COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_SHIFT Shift键按下
	COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_SHIFT COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS = 0x4
	// COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_CONTROL Ctrl键按下
	COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_CONTROL COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS = 0x8
	// COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_MIDDLE_BUTTON 中键按下
	COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_MIDDLE_BUTTON COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS = 0x10
	// COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_X_BUTTON1 第一个X键按下
	COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_X_BUTTON1 COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS = 0x20
	// COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_X_BUTTON2 第二个X键按下
	COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_X_BUTTON2 COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS = 0x40
)

// COREWEBVIEW2_POINTER_EVENT_KIND 定义了指针事件的类型
type COREWEBVIEW2_POINTER_EVENT_KIND uint32

const (
	// COREWEBVIEW2_POINTER_EVENT_KIND_ACTIVATE 表示指针激活事件
	COREWEBVIEW2_POINTER_EVENT_KIND_ACTIVATE COREWEBVIEW2_POINTER_EVENT_KIND = 587
	// COREWEBVIEW2_POINTER_EVENT_KIND_DOWN 表示指针按下事件
	COREWEBVIEW2_POINTER_EVENT_KIND_DOWN COREWEBVIEW2_POINTER_EVENT_KIND = 582
	// COREWEBVIEW2_POINTER_EVENT_KIND_ENTER 表示指针进入事件
	COREWEBVIEW2_POINTER_EVENT_KIND_ENTER COREWEBVIEW2_POINTER_EVENT_KIND = 585
	// COREWEBVIEW2_POINTER_EVENT_KIND_LEAVE 表示指针离开事件
	COREWEBVIEW2_POINTER_EVENT_KIND_LEAVE COREWEBVIEW2_POINTER_EVENT_KIND = 586
	// COREWEBVIEW2_POINTER_EVENT_KIND_UP 表示指针释放事件
	COREWEBVIEW2_POINTER_EVENT_KIND_UP COREWEBVIEW2_POINTER_EVENT_KIND = 583
	// COREWEBVIEW2_POINTER_EVENT_KIND_UPDATE 表示指针更新事件
	COREWEBVIEW2_POINTER_EVENT_KIND_UPDATE COREWEBVIEW2_POINTER_EVENT_KIND = 581
)

// COREWEBVIEW2_PRINT_ORIENTATION 定义了打印方向的类型
type COREWEBVIEW2_PRINT_ORIENTATION uint32

const (
	// COREWEBVIEW2_PRINT_ORIENTATION_PORTRAIT 纵向打印
	COREWEBVIEW2_PRINT_ORIENTATION_PORTRAIT COREWEBVIEW2_PRINT_ORIENTATION = iota
	// COREWEBVIEW2_PRINT_ORIENTATION_LANDSCAPE 横向打印
	COREWEBVIEW2_PRINT_ORIENTATION_LANDSCAPE
)

// COREWEBVIEW2_BROWSER_PROCESS_EXIT_KIND 定义了浏览器进程退出的类型
type COREWEBVIEW2_BROWSER_PROCESS_EXIT_KIND uint32

const (
	// COREWEBVIEW2_BROWSER_PROCESS_EXIT_KIND_NORMAL 表示浏览器进程正常退出
	COREWEBVIEW2_BROWSER_PROCESS_EXIT_KIND_NORMAL COREWEBVIEW2_BROWSER_PROCESS_EXIT_KIND = iota
	// COREWEBVIEW2_BROWSER_PROCESS_EXIT_KIND_FAILED 表示浏览器进程由于某些错误而退出
	COREWEBVIEW2_BROWSER_PROCESS_EXIT_KIND_FAILED
)

// COREWEBVIEW2_PROCESS_KIND 定义了 WebView2 运行时进程的类型
type COREWEBVIEW2_PROCESS_KIND uint32

const (
	// COREWEBVIEW2_PROCESS_KIND_BROWSER 浏览器进程
	COREWEBVIEW2_PROCESS_KIND_BROWSER COREWEBVIEW2_PROCESS_KIND = iota
	// COREWEBVIEW2_PROCESS_KIND_RENDERER 渲染进程
	COREWEBVIEW2_PROCESS_KIND_RENDERER
	// COREWEBVIEW2_PROCESS_KIND_UTILITY 实用工具进程
	COREWEBVIEW2_PROCESS_KIND_UTILITY
	// COREWEBVIEW2_PROCESS_KIND_SANDBOX_HELPER 沙箱辅助进程
	COREWEBVIEW2_PROCESS_KIND_SANDBOX_HELPER
	// COREWEBVIEW2_PROCESS_KIND_GPU GPU进程
	COREWEBVIEW2_PROCESS_KIND_GPU
	// COREWEBVIEW2_PROCESS_KIND_PPAPI_PLUGIN PPAPI插件进程
	COREWEBVIEW2_PROCESS_KIND_PPAPI_PLUGIN
	// COREWEBVIEW2_PROCESS_KIND_PPAPI_BROKER PPAPI代理进程
	COREWEBVIEW2_PROCESS_KIND_PPAPI_BROKER
)

// COREWEBVIEW2_FILE_SYSTEM_HANDLE_KIND 定义了文件系统句柄的类型。
type COREWEBVIEW2_FILE_SYSTEM_HANDLE_KIND uint32

const (
	// COREWEBVIEW2_FILE_SYSTEM_HANDLE_KIND_FILE 文件类型句柄。
	COREWEBVIEW2_FILE_SYSTEM_HANDLE_KIND_FILE COREWEBVIEW2_FILE_SYSTEM_HANDLE_KIND = iota
	// COREWEBVIEW2_FILE_SYSTEM_HANDLE_KIND_DIRECTORY 目录类型句柄。
	COREWEBVIEW2_FILE_SYSTEM_HANDLE_KIND_DIRECTORY
)

// COREWEBVIEW2_FILE_SYSTEM_HANDLE_PERMISSION 定义了文件系统句柄的权限。
type COREWEBVIEW2_FILE_SYSTEM_HANDLE_PERMISSION uint32

const (
	// COREWEBVIEW2_FILE_SYSTEM_HANDLE_PERMISSION_READ_ONLY 只读权限。
	COREWEBVIEW2_FILE_SYSTEM_HANDLE_PERMISSION_READ_ONLY COREWEBVIEW2_FILE_SYSTEM_HANDLE_PERMISSION = iota
	// COREWEBVIEW2_FILE_SYSTEM_HANDLE_PERMISSION_READ_WRITE 读写权限。
	COREWEBVIEW2_FILE_SYSTEM_HANDLE_PERMISSION_READ_WRITE
)

// COREWEBVIEW2_FAVICON_IMAGE_FORMAT 定义了网站图标(Favicon)的图像格式。
type COREWEBVIEW2_FAVICON_IMAGE_FORMAT uint32

const (
	// COREWEBVIEW2_FAVICON_IMAGE_FORMAT_PNG PNG格式的网站图标。
	COREWEBVIEW2_FAVICON_IMAGE_FORMAT_PNG COREWEBVIEW2_FAVICON_IMAGE_FORMAT = iota
	// COREWEBVIEW2_FAVICON_IMAGE_FORMAT_JPEG JPEG格式的网站图标。
	COREWEBVIEW2_FAVICON_IMAGE_FORMAT_JPEG
)

// COREWEBVIEW2_MEMORY_USAGE_TARGET_LEVEL 定义了 WebView2 的内存使用目标级别。
type COREWEBVIEW2_MEMORY_USAGE_TARGET_LEVEL uint32

const (
	// COREWEBVIEW2_MEMORY_USAGE_TARGET_LEVEL_NORMAL 正常内存使用级别。
	COREWEBVIEW2_MEMORY_USAGE_TARGET_LEVEL_NORMAL COREWEBVIEW2_MEMORY_USAGE_TARGET_LEVEL = iota
	// COREWEBVIEW2_MEMORY_USAGE_TARGET_LEVEL_LOW 低内存使用级别，WebView2 将尝试减少内存使用。
	COREWEBVIEW2_MEMORY_USAGE_TARGET_LEVEL_LOW
)

// COREWEBVIEW2_PREFERRED_COLOR_SCHEME 定义了 WebView2 的首选颜色方案。
type COREWEBVIEW2_PREFERRED_COLOR_SCHEME uint32

const (
	// COREWEBVIEW2_PREFERRED_COLOR_SCHEME_AUTO 自动颜色方案，WebView2 将根据系统设置自动选择颜色方案。
	COREWEBVIEW2_PREFERRED_COLOR_SCHEME_AUTO COREWEBVIEW2_PREFERRED_COLOR_SCHEME = iota
	// COREWEBVIEW2_PREFERRED_COLOR_SCHEME_LIGHT 浅色方案。
	COREWEBVIEW2_PREFERRED_COLOR_SCHEME_LIGHT
	// COREWEBVIEW2_PREFERRED_COLOR_SCHEME_DARK 深色方案。
	COREWEBVIEW2_PREFERRED_COLOR_SCHEME_DARK
)

// COREWEBVIEW2_SERVER_CERTIFICATE_ERROR_ACTION 定义了 WebView2 处理服务器证书错误的操作。
type COREWEBVIEW2_SERVER_CERTIFICATE_ERROR_ACTION uint32

const (
	// COREWEBVIEW2_SERVER_CERTIFICATE_ERROR_ACTION_ALWAYS_ALLOW 始终允许此证书，即使它有错误。
	COREWEBVIEW2_SERVER_CERTIFICATE_ERROR_ACTION_ALWAYS_ALLOW COREWEBVIEW2_SERVER_CERTIFICATE_ERROR_ACTION = iota
	// COREWEBVIEW2_SERVER_CERTIFICATE_ERROR_ACTION_CANCEL 取消请求。
	COREWEBVIEW2_SERVER_CERTIFICATE_ERROR_ACTION_CANCEL
	// COREWEBVIEW2_SERVER_CERTIFICATE_ERROR_ACTION_DEFAULT 使用默认处理方式，通常会显示警告或阻止导航。
	COREWEBVIEW2_SERVER_CERTIFICATE_ERROR_ACTION_DEFAULT
)

// COREWEBVIEW2_PRINT_STATUS 表示打印操作的状态。
//
// https://learn.microsoft.com/zh-cn/microsoft-edge/webview2/reference/win32/webview2-idl#corewebview2_print_status
type COREWEBVIEW2_PRINT_STATUS uint32

const (
	// COREWEBVIEW2_PRINT_STATUS_SUCCEEDED 打印操作成功。
	COREWEBVIEW2_PRINT_STATUS_SUCCEEDED COREWEBVIEW2_PRINT_STATUS = iota
	// COREWEBVIEW2_PRINT_STATUS_PRINTER_UNAVAILABLE 打印机不可用。
	COREWEBVIEW2_PRINT_STATUS_PRINTER_UNAVAILABLE
	// COREWEBVIEW2_PRINT_STATUS_OTHER_ERROR 打印操作失败，出现其他错误。
	COREWEBVIEW2_PRINT_STATUS_OTHER_ERROR
)

// COREWEBVIEW2_PRINT_DIALOG_KIND 表示打印对话框的类型。
//
// https://learn.microsoft.com/zh-cn/microsoft-edge/webview2/reference/win32/webview2-idl#corewebview2_print_dialog_kind
type COREWEBVIEW2_PRINT_DIALOG_KIND uint32

const (
	// COREWEBVIEW2_PRINT_DIALOG_KIND_BROWSER 使用浏览器的打印对话框。
	COREWEBVIEW2_PRINT_DIALOG_KIND_BROWSER COREWEBVIEW2_PRINT_DIALOG_KIND = iota
	// COREWEBVIEW2_PRINT_DIALOG_KIND_SYSTEM 使用系统的打印对话框。
	COREWEBVIEW2_PRINT_DIALOG_KIND_SYSTEM
)

// COREWEBVIEW2_TEXT_DIRECTION_KIND 表示文本的方向。
//
// https://learn.microsoft.com/zh-cn/microsoft-edge/webview2/reference/win32/webview2-idl#corewebview2_text_direction_kind
type COREWEBVIEW2_TEXT_DIRECTION_KIND uint32

const (
	// COREWEBVIEW2_TEXT_DIRECTION_KIND_DEFAULT 默认文本方向。
	COREWEBVIEW2_TEXT_DIRECTION_KIND_DEFAULT COREWEBVIEW2_TEXT_DIRECTION_KIND = iota
	// COREWEBVIEW2_TEXT_DIRECTION_KIND_LEFT_TO_RIGHT 从左到右的文本方向。
	COREWEBVIEW2_TEXT_DIRECTION_KIND_LEFT_TO_RIGHT
	// COREWEBVIEW2_TEXT_DIRECTION_KIND_RIGHT_TO_LEFT 从右到左的文本方向。
	COREWEBVIEW2_TEXT_DIRECTION_KIND_RIGHT_TO_LEFT
)

// COREWEBVIEW2_SAVE_AS_UI_RESULT 表示保存为UI操作的结果
type COREWEBVIEW2_SAVE_AS_UI_RESULT uint32

const (
	// COREWEBVIEW2_SAVE_AS_UI_RESULT_SUCCESS 表示保存为UI操作成功
	COREWEBVIEW2_SAVE_AS_UI_RESULT_SUCCESS COREWEBVIEW2_SAVE_AS_UI_RESULT = iota
	// COREWEBVIEW2_SAVE_AS_UI_RESULT_INVALID_PATH 表示保存路径无效
	COREWEBVIEW2_SAVE_AS_UI_RESULT_INVALID_PATH
	// COREWEBVIEW2_SAVE_AS_UI_RESULT_FILE_ALREADY_EXISTS 表示文件已存在
	COREWEBVIEW2_SAVE_AS_UI_RESULT_FILE_ALREADY_EXISTS
	// COREWEBVIEW2_SAVE_AS_UI_RESULT_KIND_NOT_SUPPORTED 表示不支持的保存类型
	COREWEBVIEW2_SAVE_AS_UI_RESULT_KIND_NOT_SUPPORTED
	// COREWEBVIEW2_SAVE_AS_UI_RESULT_CANCELLED 表示保存操作被取消
	COREWEBVIEW2_SAVE_AS_UI_RESULT_CANCELLED
)

// COREWEBVIEW2_SAVE_AS_KIND 表示保存文件的类型
type COREWEBVIEW2_SAVE_AS_KIND uint32

const (
	// COREWEBVIEW2_SAVE_AS_KIND_DEFAULT 默认保存类型
	COREWEBVIEW2_SAVE_AS_KIND_DEFAULT COREWEBVIEW2_SAVE_AS_KIND = iota
	// COREWEBVIEW2_SAVE_AS_KIND_HTML_ONLY 仅保存HTML
	COREWEBVIEW2_SAVE_AS_KIND_HTML_ONLY
	// COREWEBVIEW2_SAVE_AS_KIND_SINGLE_FILE 保存为单个文件
	COREWEBVIEW2_SAVE_AS_KIND_SINGLE_FILE
	// COREWEBVIEW2_SAVE_AS_KIND_COMPLETE 完整保存(包含所有资源)
	COREWEBVIEW2_SAVE_AS_KIND_COMPLETE
)

// COREWEBVIEW2_FRAME_KIND 定义了框架的类型
type COREWEBVIEW2_FRAME_KIND uint32

const (
	// COREWEBVIEW2_FRAME_KIND_UNKNOWN 表示未知类型的框架
	COREWEBVIEW2_FRAME_KIND_UNKNOWN COREWEBVIEW2_FRAME_KIND = iota
	// COREWEBVIEW2_FRAME_KIND_MAIN_FRAME 表示主框架（CoreWebView2）
	COREWEBVIEW2_FRAME_KIND_MAIN_FRAME
	// COREWEBVIEW2_FRAME_KIND_IFRAME 表示iframe框架
	COREWEBVIEW2_FRAME_KIND_IFRAME
	// COREWEBVIEW2_FRAME_KIND_EMBED 表示embed元素框架
	COREWEBVIEW2_FRAME_KIND_EMBED
	// COREWEBVIEW2_FRAME_KIND_OBJECT 表示object元素框架
	COREWEBVIEW2_FRAME_KIND_OBJECT
)

// COREWEBVIEW2_NON_CLIENT_REGION_KIND 定义了非客户区区域的类型
type COREWEBVIEW2_NON_CLIENT_REGION_KIND uint32

const (
	// COREWEBVIEW2_NON_CLIENT_REGION_KIND_NOWHERE 不在任何特定区域
	COREWEBVIEW2_NON_CLIENT_REGION_KIND_NOWHERE COREWEBVIEW2_NON_CLIENT_REGION_KIND = 0
	// COREWEBVIEW2_NON_CLIENT_REGION_KIND_CLIENT 客户区
	COREWEBVIEW2_NON_CLIENT_REGION_KIND_CLIENT COREWEBVIEW2_NON_CLIENT_REGION_KIND = 1
	// COREWEBVIEW2_NON_CLIENT_REGION_KIND_CAPTION 标题栏区域
	COREWEBVIEW2_NON_CLIENT_REGION_KIND_CAPTION COREWEBVIEW2_NON_CLIENT_REGION_KIND = 2
	// COREWEBVIEW2_NON_CLIENT_REGION_KIND_MINIMIZE 最小化按钮区域
	COREWEBVIEW2_NON_CLIENT_REGION_KIND_MINIMIZE COREWEBVIEW2_NON_CLIENT_REGION_KIND = 8
	// COREWEBVIEW2_NON_CLIENT_REGION_KIND_MAXIMIZE 最大化按钮区域
	COREWEBVIEW2_NON_CLIENT_REGION_KIND_MAXIMIZE COREWEBVIEW2_NON_CLIENT_REGION_KIND = 9
	// COREWEBVIEW2_NON_CLIENT_REGION_KIND_CLOSE 关闭按钮区域
	COREWEBVIEW2_NON_CLIENT_REGION_KIND_CLOSE COREWEBVIEW2_NON_CLIENT_REGION_KIND = 20
)

// COREWEBVIEW2_NAVIGATION_KIND 定义了导航类型
type COREWEBVIEW2_NAVIGATION_KIND uint32

const (
	// COREWEBVIEW2_NAVIGATION_KIND_RELOAD 表示重新加载导航
	COREWEBVIEW2_NAVIGATION_KIND_RELOAD COREWEBVIEW2_NAVIGATION_KIND = iota
	// COREWEBVIEW2_NAVIGATION_KIND_BACK_OR_FORWARD 表示后退或前进导航
	COREWEBVIEW2_NAVIGATION_KIND_BACK_OR_FORWARD
	// COREWEBVIEW2_NAVIGATION_KIND_NEW_DOCUMENT 表示新文档导航
	COREWEBVIEW2_NAVIGATION_KIND_NEW_DOCUMENT
)

// COREWEBVIEW2_PRINT_COLLATION 定义了打印排序模式。
//
// https://learn.microsoft.com/zh-cn/microsoft-edge/webview2/reference/win32/webview2-idl#corewebview2_print_collation
type COREWEBVIEW2_PRINT_COLLATION uint32

const (
	// COREWEBVIEW2_PRINT_COLLATION_DEFAULT 默认排序模式
	COREWEBVIEW2_PRINT_COLLATION_DEFAULT COREWEBVIEW2_PRINT_COLLATION = iota
	// COREWEBVIEW2_PRINT_COLLATION_COLLATED 逐份打印
	COREWEBVIEW2_PRINT_COLLATION_COLLATED
	// COREWEBVIEW2_PRINT_COLLATION_UNCOLLATED 非逐份打印
	COREWEBVIEW2_PRINT_COLLATION_UNCOLLATED
)

// COREWEBVIEW2_PRINT_COLOR_MODE 定义了打印颜色模式。
//
// https://learn.microsoft.com/zh-cn/microsoft-edge/webview2/reference/win32/webview2-idl#corewebview2_print_color_mode
type COREWEBVIEW2_PRINT_COLOR_MODE uint32

const (
	// COREWEBVIEW2_PRINT_COLOR_MODE_DEFAULT 默认颜色模式
	COREWEBVIEW2_PRINT_COLOR_MODE_DEFAULT COREWEBVIEW2_PRINT_COLOR_MODE = iota
	// COREWEBVIEW2_PRINT_COLOR_MODE_COLOR 彩色打印
	COREWEBVIEW2_PRINT_COLOR_MODE_COLOR
	// COREWEBVIEW2_PRINT_COLOR_MODE_GRAYSCALE 灰度打印
	COREWEBVIEW2_PRINT_COLOR_MODE_GRAYSCALE
)

// COREWEBVIEW2_PRINT_DUPLEX 定义了双面打印模式。
//
// https://learn.microsoft.com/zh-cn/microsoft-edge/webview2/reference/win32/webview2-idl#corewebview2_print_duplex
type COREWEBVIEW2_PRINT_DUPLEX uint32

const (
	// COREWEBVIEW2_PRINT_DUPLEX_DEFAULT 默认双面打印模式
	COREWEBVIEW2_PRINT_DUPLEX_DEFAULT COREWEBVIEW2_PRINT_DUPLEX = iota
	// COREWEBVIEW2_PRINT_DUPLEX_ONE_SIDED 单面打印
	COREWEBVIEW2_PRINT_DUPLEX_ONE_SIDED
	// COREWEBVIEW2_PRINT_DUPLEX_TWO_SIDED_LONG_EDGE 双面打印（长边装订）
	COREWEBVIEW2_PRINT_DUPLEX_TWO_SIDED_LONG_EDGE
	// COREWEBVIEW2_PRINT_DUPLEX_TWO_SIDED_SHORT_EDGE 双面打印（短边装订）
	COREWEBVIEW2_PRINT_DUPLEX_TWO_SIDED_SHORT_EDGE
)

// COREWEBVIEW2_PRINT_MEDIA_SIZE 定义了打印纸张大小。
//
// https://learn.microsoft.com/zh-cn/microsoft-edge/webview2/reference/win32/webview2-idl#corewebview2_print_media_size
type COREWEBVIEW2_PRINT_MEDIA_SIZE uint32

const (
	// COREWEBVIEW2_PRINT_MEDIA_SIZE_DEFAULT 默认纸张大小
	COREWEBVIEW2_PRINT_MEDIA_SIZE_DEFAULT COREWEBVIEW2_PRINT_MEDIA_SIZE = iota
	// COREWEBVIEW2_PRINT_MEDIA_SIZE_CUSTOM 自定义纸张大小
	COREWEBVIEW2_PRINT_MEDIA_SIZE_CUSTOM
)

// COREWEBVIEW2_PROCESS_FAILED_REASON 定义了进程失败的原因。
//
// https://learn.microsoft.com/zh-cn/microsoft-edge/webview2/reference/win32/webview2-idl#corewebview2_process_failed_reason
type COREWEBVIEW2_PROCESS_FAILED_REASON uint32

const (
	// COREWEBVIEW2_PROCESS_FAILED_REASON_UNEXPECTED 意外的进程失败
	COREWEBVIEW2_PROCESS_FAILED_REASON_UNEXPECTED COREWEBVIEW2_PROCESS_FAILED_REASON = iota
	// COREWEBVIEW2_PROCESS_FAILED_REASON_UNRESPONSIVE 进程无响应
	COREWEBVIEW2_PROCESS_FAILED_REASON_UNRESPONSIVE
	// COREWEBVIEW2_PROCESS_FAILED_REASON_TERMINATED 进程被终止
	COREWEBVIEW2_PROCESS_FAILED_REASON_TERMINATED
	// COREWEBVIEW2_PROCESS_FAILED_REASON_CRASHED 进程崩溃
	COREWEBVIEW2_PROCESS_FAILED_REASON_CRASHED
	// COREWEBVIEW2_PROCESS_FAILED_REASON_LAUNCH_FAILED 进程启动失败
	COREWEBVIEW2_PROCESS_FAILED_REASON_LAUNCH_FAILED
	// COREWEBVIEW2_PROCESS_FAILED_REASON_OUT_OF_MEMORY 进程内存不足
	COREWEBVIEW2_PROCESS_FAILED_REASON_OUT_OF_MEMORY
	// COREWEBVIEW2_PROCESS_FAILED_REASON_PROFILE_DELETED 配置文件被删除
	COREWEBVIEW2_PROCESS_FAILED_REASON_PROFILE_DELETED
)
