package edge

// todo 定义所有的IID
const (
	IID_ICoreWebView2_2  = "{B4BC1926-7305-11EE-B962-0242AC120002}"
	IID_ICoreWebView2_3  = "{A0D6DF20-3B92-416D-AA0C-437A9C727857}"
	IID_ICoreWebView2_4  = "{20D02D59-6DF2-42DC-BD06-F98A694B1302}"
	IID_ICoreWebView2_5  = "{BEDB11B8-D63C-11EB-B8BC-0242AC130003}"
	IID_ICoreWebView2_6  = "{499AADAC-D92C-4589-8A75-111BFC167795}"
	IID_ICoreWebView2_7  = "{79C24D83-09A3-45AE-9418-487F32A58740}"
	IID_ICoreWebView2_8  = "{E9632730-6E1E-43AB-B7B8-7B2C9E62E094}"
	IID_ICoreWebView2_9  = "{4D7B2EAB-9FDC-468D-B998-A9260B5ED651}"
	IID_ICoreWebView2_10 = "{B1690564-6F5A-4983-8E48-31D1143FECDB}"
	IID_ICoreWebView2_11 = "{0BE78E56-C193-4051-B943-23B460C08BDB}"
	IID_ICoreWebView2_12 = "{35D69927-BCFA-4566-9349-6B3E0D154CAC}"
	IID_ICoreWebView2_13 = "{F75F09A8-667E-4983-88D6-C8773F315E84}"
	IID_ICoreWebView2_14 = "{6DAA4F10-4A90-4753-8898-77C5DF534165}"
	IID_ICoreWebView2_15 = "{517B2D1D-7DAE-4A66-A4F4-10352FFB9518}"
	IID_ICoreWebView2_16 = "{0EB34DC9-9F91-41E1-8639-95CD5943906B}"
	IID_ICoreWebView2_17 = "{702E75D4-FD44-434D-9D70-1A68A6B1192A}"
	IID_ICoreWebView2_18 = "{7A626017-28BE-49B2-B865-3BA2B3522D90}"
	IID_ICoreWebView2_19 = "{6921F954-79B0-437F-A997-C85811897C68}"
	IID_ICoreWebView2_20 = "{B4BC1926-7305-11EE-B962-0242AC120002}"
	IID_ICoreWebView2_21 = "{C4980DEA-587B-43B9-8143-3EF3BF552D95}"
	IID_ICoreWebView2_22 = "{DB75DFC7-A857-4632-A398-6969DDE26C0A}"
	IID_ICoreWebView2_23 = "{508F0DB5-90C4-5872-90A7-267A91377502}"
	IID_ICoreWebView2_24 = "{39A7AD55-4287-5CC1-88A1-C6F458593824}"
	IID_ICoreWebView2_25 = "{B5A86092-DF50-5B4F-A17B-6C8F8B40B771}"
	IID_ICoreWebView2_26 = "{806268B8-F897-5685-88E5-C45FCA0B1A48}"
	IID_ICoreWebView2_27 = "{00FBE33B-8C07-517C-AA23-0DDD4B5F6FA0}"
)

const (
	IID_ICoreWebView2Controller2 = "{C979903E-D4CA-4228-92EB-47EE3FA96EAB}"
	IID_ICoreWebView2Controller3 = "{f9614724-5d2b-41dc-aef7-73d62b51543b}"
	IID_ICoreWebView2Controller4 = "{97d418d5-a426-4e49-a151-e1a10f327d9e}"
)

const (
	IID_ICoreWebView2Settings2 = "{EE9A0F68-F46C-4E32-AC23-EF8CAC224D2A}"
	IID_ICoreWebView2Settings3 = "{FDB5AB74-AF33-4854-84F0-0A631DEB5EBA}"
	IID_ICoreWebView2Settings4 = "{CB56846C-4168-4D53-B04F-03B6D6796FF2}"
	IID_ICoreWebView2Settings5 = "{183E7052-1D03-43A0-AB99-98E043B66B39}"
	IID_ICoreWebView2Settings6 = "{11CB3ACD-9BC8-43B8-83BF-F40753714F87}"
	IID_ICoreWebView2Settings7 = "{488DC902-35EF-42D2-BC7D-94B65C4BC49C}"
	IID_ICoreWebView2Settings8 = "{9E6B0E8F-86AD-4E81-8147-A9B5EDB68650}"
	IID_ICoreWebView2Settings9 = "{0528A73B-E92D-49F4-927A-E547DDDAA37D}"
)

const (
	IID_ICoreWebView2EnvironmentOptions  = "{2FDE08A8-1E9A-4766-8C05-95A9CEB9D1C5}"
	IID_ICoreWebView2EnvironmentOptions2 = "{FF85C98A-1BA7-4A6B-90C8-2B752C89E9E2}"
	IID_ICoreWebView2EnvironmentOptions3 = "{4A5C436E-A9E3-4A2E-89C3-910D3513F5CC}"
	IID_ICoreWebView2EnvironmentOptions4 = "{AC52D13F-0D38-475A-9DCA-876580D6793E}"
	IID_ICoreWebView2EnvironmentOptions5 = "{0AE35D64-C47F-4464-814E-259C345D1501}"
	IID_ICoreWebView2EnvironmentOptions6 = "{57D29CC3-C84F-42A0-B0E2-EFFBD5E179DE}"
	IID_ICoreWebView2EnvironmentOptions7 = "{C48D539F-E39F-441C-AE68-1F66E570BDC5}"
	IID_ICoreWebView2EnvironmentOptions8 = "{7C7ECF51-E918-5CAF-853C-E9A2BCC27775}"
)

// COREWEBVIEW2_BOUNDS_MODE 定义了边界模式类型
type COREWEBVIEW2_BOUNDS_MODE uint32

const (
	// COREWEBVIEW2_BOUNDS_MODE_USE_RAW_PIXELS 使用原始像素模式
	COREWEBVIEW2_BOUNDS_MODE_USE_RAW_PIXELS COREWEBVIEW2_BOUNDS_MODE = iota
	// COREWEBVIEW2_BOUNDS_MODE_USE_RASTERIZATION_SCALE 使用光栅化缩放模式
	COREWEBVIEW2_BOUNDS_MODE_USE_RASTERIZATION_SCALE
)

// COREWEBVIEW2_CHANNEL_SEARCH_KIND 定义了通道搜索的类型
type COREWEBVIEW2_CHANNEL_SEARCH_KIND uint32

const (
	// COREWEBVIEW2_CHANNEL_SEARCH_KIND_MOST_STABLE 表示搜索最稳定的通道
	COREWEBVIEW2_CHANNEL_SEARCH_KIND_MOST_STABLE COREWEBVIEW2_CHANNEL_SEARCH_KIND = iota
	// COREWEBVIEW2_CHANNEL_SEARCH_KIND_LEAST_STABLE 表示搜索最不稳定的通道
	COREWEBVIEW2_CHANNEL_SEARCH_KIND_LEAST_STABLE
)

// COREWEBVIEW2_RELEASE_CHANNELS 定义了 WebView2 的发布渠道类型
type COREWEBVIEW2_RELEASE_CHANNELS uint32

const (
	// COREWEBVIEW2_RELEASE_CHANNELS_NONE 无发布渠道
	COREWEBVIEW2_RELEASE_CHANNELS_NONE COREWEBVIEW2_RELEASE_CHANNELS = iota
	// COREWEBVIEW2_RELEASE_CHANNELS_STABLE 稳定版渠道
	COREWEBVIEW2_RELEASE_CHANNELS_STABLE
	// COREWEBVIEW2_RELEASE_CHANNELS_BETA 测试版渠道
	COREWEBVIEW2_RELEASE_CHANNELS_BETA
	// COREWEBVIEW2_RELEASE_CHANNELS_DEV 开发版渠道
	COREWEBVIEW2_RELEASE_CHANNELS_DEV
	// COREWEBVIEW2_RELEASE_CHANNELS_CANARY Canary 渠道
	COREWEBVIEW2_RELEASE_CHANNELS_CANARY
)

// COREWEBVIEW2_SCROLLBAR_STYLE 定义了滚动条的样式类型
type COREWEBVIEW2_SCROLLBAR_STYLE uint32

const (
	// COREWEBVIEW2_SCROLLBAR_STYLE_DEFAULT 默认滚动条样式
	COREWEBVIEW2_SCROLLBAR_STYLE_DEFAULT COREWEBVIEW2_SCROLLBAR_STYLE = iota
	// COREWEBVIEW2_SCROLLBAR_STYLE_FLUENT_OVERLAY Fluent 风格的覆盖式滚动条
	COREWEBVIEW2_SCROLLBAR_STYLE_FLUENT_OVERLAY
)

// COREWEBVIEW2_KEY_EVENT_KIND 定义了键盘事件的类型, 用于标识不同种类的键盘输入事件.
type COREWEBVIEW2_KEY_EVENT_KIND uint32

const (
	// COREWEBVIEW2_KEY_EVENT_KIND_KEY_DOWN 表示按键按下事件
	COREWEBVIEW2_KEY_EVENT_KIND_KEY_DOWN COREWEBVIEW2_KEY_EVENT_KIND = iota
	// COREWEBVIEW2_KEY_EVENT_KIND_KEY_UP 表示按键释放事件
	COREWEBVIEW2_KEY_EVENT_KIND_KEY_UP
	// COREWEBVIEW2_KEY_EVENT_KIND_SYSTEM_KEY_DOWN 表示系统按键按下事件
	COREWEBVIEW2_KEY_EVENT_KIND_SYSTEM_KEY_DOWN
	// COREWEBVIEW2_KEY_EVENT_KIND_SYSTEM_KEY_UP 表示系统按键释放事件
	COREWEBVIEW2_KEY_EVENT_KIND_SYSTEM_KEY_UP
)

// COREWEBVIEW2_PERMISSION_STATE 表示 WebView2 权限的状态
type COREWEBVIEW2_PERMISSION_STATE uint32

const (
	// COREWEBVIEW2_PERMISSION_STATE_DEFAULT 使用默认的权限设置
	COREWEBVIEW2_PERMISSION_STATE_DEFAULT COREWEBVIEW2_PERMISSION_STATE = iota
	// COREWEBVIEW2_PERMISSION_STATE_ALLOW 允许权限
	COREWEBVIEW2_PERMISSION_STATE_ALLOW
	// COREWEBVIEW2_PERMISSION_STATE_DENY 拒绝权限
	COREWEBVIEW2_PERMISSION_STATE_DENY
)

// COREWEBVIEW2_MOVE_FOCUS_REASON 定义了焦点移动的原因类型
type COREWEBVIEW2_MOVE_FOCUS_REASON uint32

const (
	// COREWEBVIEW2_MOVE_FOCUS_REASON_PROGRAMMATIC 表示通过程序代码移动焦点
	COREWEBVIEW2_MOVE_FOCUS_REASON_PROGRAMMATIC COREWEBVIEW2_MOVE_FOCUS_REASON = iota
	// COREWEBVIEW2_MOVE_FOCUS_REASON_NEXT 表示移动到下一个焦点元素
	COREWEBVIEW2_MOVE_FOCUS_REASON_NEXT
	// COREWEBVIEW2_MOVE_FOCUS_REASON_PREVIOUS 表示移动到上一个焦点元素
	COREWEBVIEW2_MOVE_FOCUS_REASON_PREVIOUS
)

// COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND 定义了资源访问的类型
type COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND uint32

const (
	// COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_DENY 拒绝访问。
	COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_DENY COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND = iota
	// COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_ALLOW 允许访问。
	COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_ALLOW
	// COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_DENY_CORS 拒绝跨域访问。
	COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_DENY_CORS
)

// COREWEBVIEW2_WEB_RESOURCE_CONTEXT 定义了 WebView2 中 Web 资源的上下文类型.
//
// 这些常量用于标识不同类型的 Web 资源请求.
type COREWEBVIEW2_WEB_RESOURCE_CONTEXT uint32

const (
	// 所有类型的资源
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_ALL COREWEBVIEW2_WEB_RESOURCE_CONTEXT = iota
	// HTML 文档
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_DOCUMENT
	// CSS 样式表
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_STYLESHEET
	// 图片资源
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_IMAGE
	// 媒体资源(音频/视频)
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_MEDIA
	// 字体资源
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_FONT
	// JavaScript 脚本
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_SCRIPT
	// XMLHttpRequest 请求
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_XML_HTTP_REQUEST
	// Fetch API 请求
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_FETCH
	// 文本轨道(字幕等)
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_TEXT_TRACK
	// EventSource API 请求
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_EVENT_SOURCE
	// WebSocket 连接
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_WEBSOCKET
	// Web 应用清单文件
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_MANIFEST
	// 签名交换
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_SIGNED_EXCHANGE
	// Ping 请求
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_PING
	// CSP 违规报告
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_CSP_VIOLATION_REPORT
	// 其他类型的资源
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_OTHER
)

// COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS 定义了 Web 资源请求的来源类型
type COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS uint32

const (
	// COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_NONE 无来源类型
	COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_NONE COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS = 0
	// COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_DOCUMENT 文档来源
	COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_DOCUMENT COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS = 0x1
	// COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_SHARED_WORKER 共享 Worker 来源
	COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_SHARED_WORKER COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS = 0x2
	// COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_SERVICE_WORKER 服务 Worker 来源
	COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_SERVICE_WORKER COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS = 0x4
	// COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_ALL 所有来源类型
	COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_ALL COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS = 0xffffffff
)

// COREWEBVIEW2_COOKIE_SAME_SITE_KIND 表示 Cookie 的 SameSite 状态。
type COREWEBVIEW2_COOKIE_SAME_SITE_KIND uint32

const (
	// COREWEBVIEW2_COOKIE_SAME_SITE_KIND_NONE: Cookie 将在所有上下文中发送，即允许跨站点发送。
	COREWEBVIEW2_COOKIE_SAME_SITE_KIND_NONE COREWEBVIEW2_COOKIE_SAME_SITE_KIND = iota
	// COREWEBVIEW2_COOKIE_SAME_SITE_KIND_LAX: Cookie 不会在跨站点请求中发送，除非是导航到目标网站的顶级导航。
	COREWEBVIEW2_COOKIE_SAME_SITE_KIND_LAX
	// COREWEBVIEW2_COOKIE_SAME_SITE_KIND_STRICT: Cookie 仅在同一站点上下文中发送。
	COREWEBVIEW2_COOKIE_SAME_SITE_KIND_STRICT
)

// COREWEBVIEW2_WEB_ERROR_STATUS 表示导航错误的状态码
type COREWEBVIEW2_WEB_ERROR_STATUS uint32

const (
	// COREWEBVIEW2_WEB_ERROR_STATUS_UNKNOWN 未知错误
	COREWEBVIEW2_WEB_ERROR_STATUS_UNKNOWN COREWEBVIEW2_WEB_ERROR_STATUS = iota
	// COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_COMMON_NAME_IS_INCORRECT 证书通用名称不正确
	COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_COMMON_NAME_IS_INCORRECT
	// COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_EXPIRED 证书已过期
	COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_EXPIRED
	// COREWEBVIEW2_WEB_ERROR_STATUS_CLIENT_CERTIFICATE_CONTAINS_ERRORS 客户端证书包含错误
	COREWEBVIEW2_WEB_ERROR_STATUS_CLIENT_CERTIFICATE_CONTAINS_ERRORS
	// COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_REVOKED 证书已被吊销
	COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_REVOKED
	// COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_IS_INVALID 证书无效
	COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_IS_INVALID
	// COREWEBVIEW2_WEB_ERROR_STATUS_SERVER_UNREACHABLE 服务器不可达
	COREWEBVIEW2_WEB_ERROR_STATUS_SERVER_UNREACHABLE
	// COREWEBVIEW2_WEB_ERROR_STATUS_TIMEOUT 连接超时
	COREWEBVIEW2_WEB_ERROR_STATUS_TIMEOUT
	// COREWEBVIEW2_WEB_ERROR_STATUS_ERROR_HTTP_INVALID_SERVER_RESPONSE 无效的服务器响应
	COREWEBVIEW2_WEB_ERROR_STATUS_ERROR_HTTP_INVALID_SERVER_RESPONSE
	// COREWEBVIEW2_WEB_ERROR_STATUS_CONNECTION_ABORTED 连接中止
	COREWEBVIEW2_WEB_ERROR_STATUS_CONNECTION_ABORTED
	// COREWEBVIEW2_WEB_ERROR_STATUS_CONNECTION_RESET 连接重置
	COREWEBVIEW2_WEB_ERROR_STATUS_CONNECTION_RESET
	// COREWEBVIEW2_WEB_ERROR_STATUS_DISCONNECTED 已断开连接
	COREWEBVIEW2_WEB_ERROR_STATUS_DISCONNECTED
	// COREWEBVIEW2_WEB_ERROR_STATUS_CANNOT_CONNECT 无法连接
	COREWEBVIEW2_WEB_ERROR_STATUS_CANNOT_CONNECT
	// COREWEBVIEW2_WEB_ERROR_STATUS_HOST_NAME_NOT_RESOLVED 主机名无法解析
	COREWEBVIEW2_WEB_ERROR_STATUS_HOST_NAME_NOT_RESOLVED
	// COREWEBVIEW2_WEB_ERROR_STATUS_OPERATION_CANCELED 操作已取消
	COREWEBVIEW2_WEB_ERROR_STATUS_OPERATION_CANCELED
	// COREWEBVIEW2_WEB_ERROR_STATUS_REDIRECT_FAILED 重定向失败
	COREWEBVIEW2_WEB_ERROR_STATUS_REDIRECT_FAILED
	// COREWEBVIEW2_WEB_ERROR_STATUS_UNEXPECTED_ERROR 意外错误
	COREWEBVIEW2_WEB_ERROR_STATUS_UNEXPECTED_ERROR
	// COREWEBVIEW2_WEB_ERROR_STATUS_VALID_AUTHENTICATION_CREDENTIALS_REQUIRED 指示提示用户登录，等待用户操作
	COREWEBVIEW2_WEB_ERROR_STATUS_VALID_AUTHENTICATION_CREDENTIALS_REQUIRED
	// COREWEBVIEW2_WEB_ERROR_STATUS_VALID_PROXY_AUTHENTICATION_REQUIRED 指示用户缺少代理服务器的正确身份验证凭据
	COREWEBVIEW2_WEB_ERROR_STATUS_VALID_PROXY_AUTHENTICATION_REQUIRED
)

// COREWEBVIEW2_PERMISSION_KIND 定义了 WebView2 中的权限类型
type COREWEBVIEW2_PERMISSION_KIND uint32

const (
	// COREWEBVIEW2_PERMISSION_KIND_UNKNOWN_PERMISSION 未知权限
	COREWEBVIEW2_PERMISSION_KIND_UNKNOWN_PERMISSION COREWEBVIEW2_PERMISSION_KIND = iota
	// COREWEBVIEW2_PERMISSION_KIND_MICROPHONE 麦克风权限
	COREWEBVIEW2_PERMISSION_KIND_MICROPHONE
	// COREWEBVIEW2_PERMISSION_KIND_CAMERA 摄像头权限
	COREWEBVIEW2_PERMISSION_KIND_CAMERA
	// COREWEBVIEW2_PERMISSION_KIND_GEOLOCATION 地理位置权限
	COREWEBVIEW2_PERMISSION_KIND_GEOLOCATION
	// COREWEBVIEW2_PERMISSION_KIND_NOTIFICATIONS 通知权限
	COREWEBVIEW2_PERMISSION_KIND_NOTIFICATIONS
	// COREWEBVIEW2_PERMISSION_KIND_OTHER_SENSORS 其他传感器权限
	COREWEBVIEW2_PERMISSION_KIND_OTHER_SENSORS
	// COREWEBVIEW2_PERMISSION_KIND_CLIPBOARD_READ 剪贴板读取权限
	COREWEBVIEW2_PERMISSION_KIND_CLIPBOARD_READ
	// COREWEBVIEW2_PERMISSION_KIND_MULTIPLE_AUTOMATIC_DOWNLOADS 表示自动下载多个文件的权限
	COREWEBVIEW2_PERMISSION_KIND_MULTIPLE_AUTOMATIC_DOWNLOADS
	// COREWEBVIEW2_PERMISSION_KIND_FILE_READ_WRITE 表示读写设备上的文件或文件夹的权限
	COREWEBVIEW2_PERMISSION_KIND_FILE_READ_WRITE
	// COREWEBVIEW2_PERMISSION_KIND_AUTOPLAY 表示在网站上自动播放音频和视频的权限
	COREWEBVIEW2_PERMISSION_KIND_AUTOPLAY
	// COREWEBVIEW2_PERMISSION_KIND_LOCAL_FONTS 表示使用设备上字体的权限
	COREWEBVIEW2_PERMISSION_KIND_LOCAL_FONTS
	// COREWEBVIEW2_PERMISSION_KIND_MIDI_SYSTEM_EXCLUSIVE_MESSAGES 表示向/从MIDI设备发送和接收系统专有消息的权限
	COREWEBVIEW2_PERMISSION_KIND_MIDI_SYSTEM_EXCLUSIVE_MESSAGES
	// COREWEBVIEW2_PERMISSION_KIND_WINDOW_MANAGEMENT 表示在屏幕上打开和放置窗口的权限
	COREWEBVIEW2_PERMISSION_KIND_WINDOW_MANAGEMENT
)

// COREWEBVIEW2_PDF_TOOLBAR_ITEMS 定义了 PDF 工具栏中可用的项目
type COREWEBVIEW2_PDF_TOOLBAR_ITEMS uint32

const (
	// COREWEBVIEW2_PDF_TOOLBAR_ITEMS_NONE 不显示任何工具栏项目
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_NONE COREWEBVIEW2_PDF_TOOLBAR_ITEMS = iota
	// COREWEBVIEW2_PDF_TOOLBAR_ITEMS_SAVE 保存按钮
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_SAVE
	// COREWEBVIEW2_PDF_TOOLBAR_ITEMS_PRINT 打印按钮
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_PRINT
	// COREWEBVIEW2_PDF_TOOLBAR_ITEMS_SAVE_AS 另存为按钮
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_SAVE_AS
	// COREWEBVIEW2_PDF_TOOLBAR_ITEMS_ZOOM_IN 放大按钮
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_ZOOM_IN
	// COREWEBVIEW2_PDF_TOOLBAR_ITEMS_ZOOM_OUT 缩小按钮
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_ZOOM_OUT
	// COREWEBVIEW2_PDF_TOOLBAR_ITEMS_ROTATE 旋转按钮
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_ROTATE
	// COREWEBVIEW2_PDF_TOOLBAR_ITEMS_FIT_PAGE 适应页面按钮
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_FIT_PAGE
	// COREWEBVIEW2_PDF_TOOLBAR_ITEMS_PAGE_LAYOUT 页面布局按钮
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_PAGE_LAYOUT
	// COREWEBVIEW2_PDF_TOOLBAR_ITEMS_BOOKMARKS 书签按钮
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_BOOKMARKS
	// COREWEBVIEW2_PDF_TOOLBAR_ITEMS_PAGE_SELECTOR 页面选择按钮
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_PAGE_SELECTOR
	// COREWEBVIEW2_PDF_TOOLBAR_ITEMS_SEARCH 搜索按钮
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_SEARCH
	// COREWEBVIEW2_PDF_TOOLBAR_ITEMS_FULL_SCREEN 全屏按钮
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_FULL_SCREEN
	// COREWEBVIEW2_PDF_TOOLBAR_ITEMS_MORE_SETTINGS 更多设置按钮
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_MORE_SETTINGS
)

// COREWEBVIEW2_TRACKING_PREVENTION_LEVEL 定义了跟踪防护的级别
type COREWEBVIEW2_TRACKING_PREVENTION_LEVEL uint32

const (
	// COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_NONE 关闭跟踪防护
	COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_NONE COREWEBVIEW2_TRACKING_PREVENTION_LEVEL = iota
	// COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_BASIC 最低限制级别的跟踪防护
	COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_BASIC
	// COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_BALANCED 默认级别的跟踪防护
	COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_BALANCED
	// COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_STRICT 最严格级别的跟踪防护
	COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_STRICT
)
